USE CineDB;

SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE Boleto;
TRUNCATE TABLE Compra;
TRUNCATE TABLE Dulceria;
TRUNCATE TABLE Funcion;
TRUNCATE TABLE Pelicula;
TRUNCATE TABLE Sala;
TRUNCATE TABLE Socio;
TRUNCATE TABLE Cliente;
TRUNCATE TABLE Sede;

SET FOREIGN_KEY_CHECKS = 1;
